/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package reservaruralapp;

import util.DBConnection;
import java.sql.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;

public class PanelClientes extends javax.swing.JPanel {

   
    public PanelClientes() {
        initComponents();
      
    ControlAcceso.aplicarPermisos(BotonNuevoCliente, BotonEliminarCliente);
}
    
private void cargarClientes() {
    DefaultTableModel modelo = (DefaultTableModel) TablaClientes.getModel();
    modelo.setRowCount(0);

    String sql = "SELECT * FROM cliente";

    try (Connection conn = DBConnection.getConnection();
         Statement stmt = conn.createStatement();
         ResultSet rs = stmt.executeQuery(sql)) {

        while (rs.next()) {
            Object[] fila = new Object[]{
                rs.getInt("id_cliente"),
                rs.getString("nombre"),
                rs.getString("apellidos"),
                rs.getString("DNI"),
                rs.getString("telefono"),
                rs.getString("email"),
                rs.getString("comentarios")
            };
            modelo.addRow(fila);
        }

    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Error al cargar clientes: " + e.getMessage());
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelClientes = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        BotonNuevoCliente = new javax.swing.JButton();
        GuardarCliente = new javax.swing.JButton();
        BotonVerDetalles = new javax.swing.JButton();
        BotonLupaCliente = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        LabelClientes = new javax.swing.JLabel();
        CampoBuscarCliente = new javax.swing.JTextField();
        BotonEliminarCliente = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        scrolltablaclientes = new javax.swing.JScrollPane();
        TablaClientes = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelClientes.setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        BotonNuevoCliente.setBackground(new java.awt.Color(241, 250, 241));
        BotonNuevoCliente.setForeground(new java.awt.Color(51, 102, 0));
        BotonNuevoCliente.setText("Agregar Cliente");
        BotonNuevoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonNuevoClienteActionPerformed(evt);
            }
        });

        GuardarCliente.setBackground(new java.awt.Color(241, 250, 241));
        GuardarCliente.setForeground(new java.awt.Color(51, 102, 0));
        GuardarCliente.setText("Guardar");
        GuardarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarClienteActionPerformed(evt);
            }
        });

        BotonVerDetalles.setBackground(new java.awt.Color(241, 250, 241));
        BotonVerDetalles.setForeground(new java.awt.Color(51, 102, 0));
        BotonVerDetalles.setText("Ver Clientes");
        BotonVerDetalles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonVerDetallesActionPerformed(evt);
            }
        });

        BotonLupaCliente.setBackground(new java.awt.Color(241, 250, 241));
        BotonLupaCliente.setForeground(new java.awt.Color(51, 102, 0));
        BotonLupaCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/lupa.png"))); // NOI18N
        BotonLupaCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonLupaClienteActionPerformed(evt);
            }
        });

        jSeparator2.setBackground(new java.awt.Color(0, 102, 51));
        jSeparator2.setForeground(new java.awt.Color(0, 102, 51));

        LabelClientes.setText("CLIENTES");

        CampoBuscarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoBuscarClienteActionPerformed(evt);
            }
        });

        BotonEliminarCliente.setBackground(new java.awt.Color(241, 250, 241));
        BotonEliminarCliente.setForeground(new java.awt.Color(51, 102, 0));
        BotonEliminarCliente.setText("Eliminar Cliente");
        BotonEliminarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonEliminarClienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jSeparator2)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(LabelClientes))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(BotonVerDetalles)
                        .addGap(50, 50, 50)
                        .addComponent(BotonNuevoCliente)
                        .addGap(45, 45, 45)
                        .addComponent(GuardarCliente)
                        .addGap(49, 49, 49)
                        .addComponent(BotonEliminarCliente)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(CampoBuscarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BotonLupaCliente)
                .addGap(103, 103, 103))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(LabelClientes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BotonVerDetalles)
                            .addComponent(GuardarCliente)
                            .addComponent(BotonNuevoCliente)
                            .addComponent(CampoBuscarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BotonEliminarCliente)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(BotonLupaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        TablaClientes.setBackground(new java.awt.Color(204, 255, 204));
        TablaClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "id_cliente", "nombre", "apellidos", "DNI", "telefono", "email", "comentarios"
            }
        ));
        scrolltablaclientes.setViewportView(TablaClientes);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrolltablaclientes, javax.swing.GroupLayout.PREFERRED_SIZE, 1133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrolltablaclientes, javax.swing.GroupLayout.PREFERRED_SIZE, 523, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout PanelClientesLayout = new javax.swing.GroupLayout(PanelClientes);
        PanelClientes.setLayout(PanelClientesLayout);
        PanelClientesLayout.setHorizontalGroup(
            PanelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelClientesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelClientesLayout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 10, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        PanelClientesLayout.setVerticalGroup(
            PanelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelClientesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        add(PanelClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 5, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void BotonNuevoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonNuevoClienteActionPerformed
     DefaultTableModel modelo = (DefaultTableModel) TablaClientes.getModel();
    // Agrega una fila vacía con todos los valores null (ID se asignará al guardar)
    modelo.addRow(new Object[]{null, null, null, null, null, null, null});
    
    // Selecciona automáticamente la fila recién agregada
    int fila = modelo.getRowCount() - 1;
    TablaClientes.setRowSelectionInterval(fila, fila);
    }//GEN-LAST:event_BotonNuevoClienteActionPerformed

    private void GuardarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarClienteActionPerformed
        DefaultTableModel modelo = (DefaultTableModel) TablaClientes.getModel();

    try (Connection conn = DBConnection.getConnection()) {
        for (int i = 0; i < modelo.getRowCount(); i++) {
            Object idObj = modelo.getValueAt(i, 0);
            int id = (idObj instanceof Integer) ? (Integer) idObj : 0;

            // Normalización a MAYÚSCULAS
            String nombre = InputUtils.normalizarMayusculas(modelo.getValueAt(i, 1) != null ? modelo.getValueAt(i, 1).toString() : null);
            String apellidos = InputUtils.normalizarMayusculas(modelo.getValueAt(i, 2) != null ? modelo.getValueAt(i, 2).toString() : null);
            String dni = InputUtils.normalizarMayusculas(modelo.getValueAt(i, 3) != null ? modelo.getValueAt(i, 3).toString() : null);
                if (dni != null && !dni.isEmpty() && !InputUtils.validaDNI(dni)) {
                    JOptionPane.showMessageDialog(this, "El DNI de la fila " + (i+1) + " no es válido: " + dni);
                    return; // no guarda si algún DNI es incorrecto
                }
            String telefono = InputUtils.normalizarMayusculas(modelo.getValueAt(i, 4) != null 
                        ? modelo.getValueAt(i, 4).toString() 
                        : null);

                if (telefono != null && !telefono.isEmpty() && !InputUtils.validaTelefonoE164(telefono)) {
                    JOptionPane.showMessageDialog(this, "El teléfono de la fila " + (i+1) + " no es válido: " + telefono);
                    return;
                }
            String email = InputUtils.normalizarMayusculas(
                        modelo.getValueAt(i, 5) != null ? modelo.getValueAt(i, 5).toString() : null
                );
                if (email != null && !email.isEmpty() && !InputUtils.validaEmail(email)) {
                    JOptionPane.showMessageDialog(this, "El email no es válido: " + email);
                    return; 
                }

            String comentarios = InputUtils.normalizarMayusculas(modelo.getValueAt(i, 6) != null ? modelo.getValueAt(i, 6).toString() : null);

            if (id == 0) {
                String sql = "INSERT INTO cliente (nombre, apellidos, DNI, telefono, email, comentarios) VALUES (?, ?, ?, ?, ?, ?)";
                try (PreparedStatement ps = conn.prepareStatement(sql)) {
                    ps.setString(1, nombre);
                    ps.setString(2, apellidos);
                    ps.setString(3, dni);
                    ps.setString(4, telefono);
                    ps.setString(5, email);
                    ps.setString(6, comentarios);
                    ps.executeUpdate();
                }
            } else {
                String sql = "UPDATE cliente SET nombre=?, apellidos=?, DNI=?, telefono=?, email=?, comentarios=? WHERE id_cliente=?";
                try (PreparedStatement ps = conn.prepareStatement(sql)) {
                    ps.setString(1, nombre);
                    ps.setString(2, apellidos);
                    ps.setString(3, dni);
                    ps.setString(4, telefono);
                    ps.setString(5, email);
                    ps.setString(6, comentarios);
                    ps.setInt(7, id);
                    ps.executeUpdate();
                }
            }
        }

        JOptionPane.showMessageDialog(this, "Cambios guardados correctamente.");
        cargarClientes();

    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Error al guardar clientes: " + e.getMessage());
    }
    }//GEN-LAST:event_GuardarClienteActionPerformed

    private void BotonVerDetallesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonVerDetallesActionPerformed
        cargarClientes();
    }//GEN-LAST:event_BotonVerDetallesActionPerformed

    private void BotonLupaClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonLupaClienteActionPerformed
      String textoBusqueda = InputUtils.normalizarMayusculas(CampoBuscarCliente.getText().trim());

    if (textoBusqueda.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Introduce un texto para buscar.");
        return;
    }

    DefaultTableModel modelo = (DefaultTableModel) TablaClientes.getModel();
    modelo.setRowCount(0);

    String sql = "SELECT * FROM cliente WHERE "
               + "UPPER(nombre) LIKE ? OR "
               + "UPPER(apellidos) LIKE ? OR "
               + "UPPER(DNI) LIKE ? OR "
               + "UPPER(telefono) LIKE ? OR "
               + "UPPER(email) LIKE ? OR "
               + "UPPER(comentarios) LIKE ?";

    try (Connection conn = DBConnection.getConnection();
         PreparedStatement ps = conn.prepareStatement(sql)) {

        for (int i = 1; i <= 6; i++) {
            ps.setString(i, "%" + textoBusqueda + "%");
        }

        ResultSet rs = ps.executeQuery();
        boolean hayResultados = false;

        while (rs.next()) {
            Object[] fila = new Object[]{
                rs.getInt("id_cliente"),
                rs.getString("nombre"),
                rs.getString("apellidos"),
                rs.getString("DNI"),
                rs.getString("telefono"),
                rs.getString("email"),
                rs.getString("comentarios")
            };
            modelo.addRow(fila);
            hayResultados = true;
        }

        if (!hayResultados) {
            JOptionPane.showMessageDialog(this, "No se encontraron clientes con ese criterio.");
        }

    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Error al buscar clientes: " + e.getMessage());
    }
    }//GEN-LAST:event_BotonLupaClienteActionPerformed

    private void CampoBuscarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoBuscarClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoBuscarClienteActionPerformed

    private void BotonEliminarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonEliminarClienteActionPerformed
    int fila = TablaClientes.getSelectedRow();
    if (fila == -1) {
        JOptionPane.showMessageDialog(this, "Selecciona un cliente para eliminar.");
        return;
    }

    int id = (int) TablaClientes.getValueAt(fila, 0); // eliminar por ID
    int confirmar = JOptionPane.showConfirmDialog(this, "¿Seguro que quieres eliminar este cliente?", "Confirmar", JOptionPane.YES_NO_OPTION);
    if (confirmar != JOptionPane.YES_OPTION) return;

    String sql = "DELETE FROM cliente WHERE id_cliente=?";
    try (Connection conn = DBConnection.getConnection();
         PreparedStatement ps = conn.prepareStatement(sql)) {
        ps.setInt(1, id);
        ps.executeUpdate();
        JOptionPane.showMessageDialog(this, "Cliente eliminado correctamente.");
        cargarClientes();
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Error al eliminar cliente: " + e.getMessage());
    }
    }//GEN-LAST:event_BotonEliminarClienteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonEliminarCliente;
    private javax.swing.JButton BotonLupaCliente;
    private javax.swing.JButton BotonNuevoCliente;
    private javax.swing.JButton BotonVerDetalles;
    private javax.swing.JTextField CampoBuscarCliente;
    private javax.swing.JButton GuardarCliente;
    private javax.swing.JLabel LabelClientes;
    private javax.swing.JPanel PanelClientes;
    private javax.swing.JTable TablaClientes;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JScrollPane scrolltablaclientes;
    // End of variables declaration//GEN-END:variables
}

