/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package reservaruralapp;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import util.DBConnection;



/**
 *
 * @author jimen
 */
public class PanelOpciones extends javax.swing.JPanel {

    /**
     * Creates new form PanelOpciones
     */
    public PanelOpciones() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelOpciones = new javax.swing.JPanel();
        LabelOpciones = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        BotonGuardarOpciones = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        TextoNombreOpciones = new javax.swing.JTextField();
        TextoContraseñaOpciones = new javax.swing.JTextField();
        BotonBuscarOpciones = new javax.swing.JButton();
        BotonEliminarOpciones = new javax.swing.JButton();
        AdminRecepcionista = new javax.swing.JComboBox<>();

        LabelOpciones.setText(" OPCIONES USUARIO:");

        jSeparator3.setBackground(new java.awt.Color(0, 102, 51));
        jSeparator3.setForeground(new java.awt.Color(0, 102, 51));

        BotonGuardarOpciones.setText("Guardar");
        BotonGuardarOpciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonGuardarOpcionesActionPerformed(evt);
            }
        });

        jLabel1.setText("Nombre:");

        jLabel3.setText("Contraseña:");

        jLabel4.setText("Rol:");

        TextoNombreOpciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextoNombreOpcionesActionPerformed(evt);
            }
        });

        TextoContraseñaOpciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextoContraseñaOpcionesActionPerformed(evt);
            }
        });

        BotonBuscarOpciones.setText("Buscar");
        BotonBuscarOpciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonBuscarOpcionesActionPerformed(evt);
            }
        });

        BotonEliminarOpciones.setText("Eliminar Usuario");
        BotonEliminarOpciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonEliminarOpcionesActionPerformed(evt);
            }
        });

        AdminRecepcionista.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "admin", "recepcionista" }));
        AdminRecepcionista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdminRecepcionistaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelOpcionesLayout = new javax.swing.GroupLayout(PanelOpciones);
        PanelOpciones.setLayout(PanelOpcionesLayout);
        PanelOpcionesLayout.setHorizontalGroup(
            PanelOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelOpcionesLayout.createSequentialGroup()
                .addGroup(PanelOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelOpcionesLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(PanelOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabelOpciones)
                            .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 950, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(PanelOpcionesLayout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(PanelOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelOpcionesLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(TextoNombreOpciones, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PanelOpcionesLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(26, 26, 26)
                                .addComponent(TextoContraseñaOpciones, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PanelOpcionesLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(45, 45, 45)
                                .addComponent(AdminRecepcionista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PanelOpcionesLayout.createSequentialGroup()
                                .addComponent(BotonBuscarOpciones)
                                .addGap(115, 115, 115)
                                .addComponent(BotonGuardarOpciones)
                                .addGap(36, 36, 36)
                                .addComponent(BotonEliminarOpciones)))))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        PanelOpcionesLayout.setVerticalGroup(
            PanelOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelOpcionesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabelOpciones)
                .addGap(32, 32, 32)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addGroup(PanelOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(TextoNombreOpciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(PanelOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(TextoContraseñaOpciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(PanelOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(AdminRecepcionista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(70, 70, 70)
                .addGroup(PanelOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotonBuscarOpciones)
                    .addComponent(BotonGuardarOpciones)
                    .addComponent(BotonEliminarOpciones))
                .addContainerGap(251, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1011, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(PanelOpciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 550, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(PanelOpciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BotonGuardarOpcionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonGuardarOpcionesActionPerformed
        String username = TextoNombreOpciones.getText().trim().toUpperCase();
        String password = TextoContraseñaOpciones.getText().trim().toUpperCase();
        String rol = AdminRecepcionista.getSelectedItem().toString().trim().toLowerCase();


        if (username.isEmpty() || password.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Nombre y contraseña son obligatorios.", "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }

        String sqlCheck = "SELECT * FROM usuario WHERE UPPER(username) = UPPER(?)";

        try (Connection conn = DBConnection.getConnection();
             PreparedStatement psCheck = conn.prepareStatement(sqlCheck)) {

            psCheck.setString(1, username);
            ResultSet rs = psCheck.executeQuery();

            if (rs.next()) {
                // UPDATE
                String sqlUpdate = "UPDATE usuario SET password = ?, rol = ? WHERE UPPER(username) = UPPER(?)";

                try (PreparedStatement psUpdate = conn.prepareStatement(sqlUpdate)) {
                    psUpdate.setString(1, password);
                    psUpdate.setString(2, rol);
                    psUpdate.setString(3, username);
                    psUpdate.executeUpdate();

                    JOptionPane.showMessageDialog(this, "Usuario actualizado correctamente.");
                }

            } else {
                // INSERT
                String sqlInsert = "INSERT INTO usuario(username, password, rol) VALUES(?,?,?)";

                try (PreparedStatement psInsert = conn.prepareStatement(sqlInsert)) {
                    psInsert.setString(1, username);
                    psInsert.setString(2, password);
                    psInsert.setString(3, rol);
                    psInsert.executeUpdate();

                    JOptionPane.showMessageDialog(this, "Usuario creado correctamente.");
                }
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        }
    

    }//GEN-LAST:event_BotonGuardarOpcionesActionPerformed

    private void TextoNombreOpcionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextoNombreOpcionesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextoNombreOpcionesActionPerformed

    private void TextoContraseñaOpcionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextoContraseñaOpcionesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextoContraseñaOpcionesActionPerformed

    private void BotonBuscarOpcionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonBuscarOpcionesActionPerformed
         String nombre = TextoNombreOpciones.getText().trim().toUpperCase();

        if (nombre.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Introduce un nombre para buscar.");
            return;
        }

        String sql = "SELECT * FROM usuario WHERE UPPER(username) = UPPER(?)";

        try (Connection conn = DBConnection.getConnection();
             PreparedStatement ps = conn.prepareStatement(sql)) {

            ps.setString(1, nombre);
            ResultSet rs = ps.executeQuery();

            if (rs.next()) {
                TextoContraseñaOpciones.setText(rs.getString("password"));
                AdminRecepcionista.setSelectedItem(rs.getString("rol").toUpperCase());
            } else {
                TextoContraseñaOpciones.setText("");
                AdminRecepcionista.setSelectedIndex(0);
                JOptionPane.showMessageDialog(this, "Usuario no encontrado.");
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error al buscar usuario: " + e.getMessage());
        }
    
    }//GEN-LAST:event_BotonBuscarOpcionesActionPerformed

    private void BotonEliminarOpcionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonEliminarOpcionesActionPerformed
         String nombre = TextoNombreOpciones.getText().trim().toUpperCase();

        if (nombre.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Introduce un nombre para eliminar.");
            return;
        }

        String sql = "DELETE FROM usuario WHERE UPPER(username) = UPPER(?)";

        try (Connection conn = DBConnection.getConnection();
             PreparedStatement ps = conn.prepareStatement(sql)) {

            ps.setString(1, nombre);
            int filas = ps.executeUpdate();

            if (filas > 0) {
                JOptionPane.showMessageDialog(this, "Usuario eliminado correctamente.");
                TextoNombreOpciones.setText("");
                TextoContraseñaOpciones.setText("");
                AdminRecepcionista.setSelectedIndex(0);
            } else {
                JOptionPane.showMessageDialog(this, "No se encontró el usuario para eliminar.");
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error al eliminar usuario: " + e.getMessage());
        }
    }//GEN-LAST:event_BotonEliminarOpcionesActionPerformed

    private void AdminRecepcionistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdminRecepcionistaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AdminRecepcionistaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> AdminRecepcionista;
    private javax.swing.JButton BotonBuscarOpciones;
    private javax.swing.JButton BotonEliminarOpciones;
    private javax.swing.JButton BotonGuardarOpciones;
    private javax.swing.JLabel LabelOpciones;
    private javax.swing.JPanel PanelOpciones;
    private javax.swing.JTextField TextoContraseñaOpciones;
    private javax.swing.JTextField TextoNombreOpciones;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JSeparator jSeparator3;
    // End of variables declaration//GEN-END:variables
}
