/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package reservaruralapp;

/**
 *
 * @author jimen
 */
public class PanelCasas extends javax.swing.JPanel {

    /**
     * Creates new form PanelCasas
     */
    public PanelCasas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelCasas = new javax.swing.JPanel();
        LabelCasas = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        BotonNuevaCasa = new javax.swing.JButton();
        BotonEditarCasa = new javax.swing.JButton();
        BotonEliminarCasa = new javax.swing.JButton();
        BotonBuscarCasa = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JSeparator();
        ScrollPanelCasas = new javax.swing.JScrollPane();
        TableCasas = new javax.swing.JTable();

        LabelCasas.setText("CASAS");

        BotonNuevaCasa.setText("Nueva Casa");
        BotonNuevaCasa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonNuevaCasaActionPerformed(evt);
            }
        });

        BotonEditarCasa.setText("Editar Casa");
        BotonEditarCasa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonEditarCasaActionPerformed(evt);
            }
        });

        BotonEliminarCasa.setText("Eliminar Casa");
        BotonEliminarCasa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonEliminarCasaActionPerformed(evt);
            }
        });

        BotonBuscarCasa.setText("Buscar Casa");
        BotonBuscarCasa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonBuscarCasaActionPerformed(evt);
            }
        });

        jSeparator4.setBackground(new java.awt.Color(0, 102, 51));
        jSeparator4.setForeground(new java.awt.Color(0, 102, 51));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(BotonNuevaCasa)
                .addGap(26, 26, 26)
                .addComponent(BotonEditarCasa)
                .addGap(32, 32, 32)
                .addComponent(BotonEliminarCasa)
                .addGap(37, 37, 37)
                .addComponent(BotonBuscarCasa)
                .addContainerGap(506, Short.MAX_VALUE))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator4)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotonNuevaCasa)
                    .addComponent(BotonEditarCasa)
                    .addComponent(BotonEliminarCasa)
                    .addComponent(BotonBuscarCasa))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        TableCasas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "id_casa", "Nombre", "Ubicacion", "Capacidad", "Precio Noche", "Descripcion"
            }
        ));
        ScrollPanelCasas.setViewportView(TableCasas);

        javax.swing.GroupLayout PanelCasasLayout = new javax.swing.GroupLayout(PanelCasas);
        PanelCasas.setLayout(PanelCasasLayout);
        PanelCasasLayout.setHorizontalGroup(
            PanelCasasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelCasasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelCasasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(PanelCasasLayout.createSequentialGroup()
                        .addComponent(LabelCasas)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(PanelCasasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PanelCasasLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(ScrollPanelCasas, javax.swing.GroupLayout.DEFAULT_SIZE, 999, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        PanelCasasLayout.setVerticalGroup(
            PanelCasasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelCasasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabelCasas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(445, Short.MAX_VALUE))
            .addGroup(PanelCasasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelCasasLayout.createSequentialGroup()
                    .addContainerGap(107, Short.MAX_VALUE)
                    .addComponent(ScrollPanelCasas, javax.swing.GroupLayout.PREFERRED_SIZE, 437, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1011, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(PanelCasas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 550, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(PanelCasas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BotonNuevaCasaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonNuevaCasaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonNuevaCasaActionPerformed

    private void BotonEditarCasaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonEditarCasaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonEditarCasaActionPerformed

    private void BotonEliminarCasaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonEliminarCasaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonEliminarCasaActionPerformed

    private void BotonBuscarCasaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonBuscarCasaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonBuscarCasaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonBuscarCasa;
    private javax.swing.JButton BotonEditarCasa;
    private javax.swing.JButton BotonEliminarCasa;
    private javax.swing.JButton BotonNuevaCasa;
    private javax.swing.JLabel LabelCasas;
    private javax.swing.JPanel PanelCasas;
    private javax.swing.JScrollPane ScrollPanelCasas;
    private javax.swing.JTable TableCasas;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JSeparator jSeparator4;
    // End of variables declaration//GEN-END:variables
}
